# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Academic Competition Federation
tagline: Hi. Weâ€™re ACF.
description: We produce three high-quality collegiate quizbowl tournaments each year. Our organization is completely student and volunteer-run, by quizbowl players, for quizbowl players. Our tournaments are written to reward academic knowledge, encourage learning, and foster the spirit of competition and fair play.
logo: /logo.png
thumbnail: /thumbnail_logo.png
baseurl: "" # the subpath of your site, e.g. /blog
url: "acf-quizbowl.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: acf-quizbowl.github.io # the GitHub repo name for your project
github_username: acf-quizbowl

plugins: 
  - jekyll-swiss

remote_theme: broccolini/swiss

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: facebook
social_username: acfqb

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: acf

# Build settings
markdown: kramdown
